plugins {
    id 'org.relativitymc.neo-loom-remap'
    id 'java-library'
    id 'maven-publish'
    id 'idea'
}

group = project.mod_group
version = project.mod_version

base {
    archivesName = "${project.mod_id}-${project.name}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(project.java_version)

repositories {
    // Add additional repositories here if a dependency requires them.
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
}

jar {
    from(rootProject.file('LICENSE'))
}

processResources {
    var replaceProperties = [
            mod_id                 : mod_id,
            mod_group              : mod_group,
            mod_version            : mod_version,
            mod_name               : mod_name,
            mod_description        : mod_description,
            mod_author             : mod_author,
            mod_credits            : mod_credits,
            mod_homepage           : mod_homepage,
            mod_github             : mod_github,
            mod_license            : mod_license,
            mod_icon               : mod_icon,
            java_version           : java_version,
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            fabric_loader_version  : fabric_loader_version,
            fabric_api_version     : fabric_api_version,
            forge_version          : forge_version,
            forge_version_range    : forge_version_range,
            neoforge_version       : neoforge_version
    ]

    var jsonReplaceProperties = replaceProperties.collectEntries {
        key, value -> [(key): value instanceof String ? value.replace("\n", "\\\\n") : value]
    }

    filesMatching(['META-INF/mods.toml', 'META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }

    filesMatching(['pack.mcmeta', 'fabric.mod.json', '*.mixins.json']) {
        expand jsonReplaceProperties
    }

    inputs.properties replaceProperties
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}