# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Environment Properties
java_version=25
minecraft_version=26.1
minecraft_version_range=[26.1, 26.2)

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_loader_version=0.19.2
fabric_api_version=0.145.1+26.1

# Forge, see https://files.minecraftforge.net/net/minecraftforge/forge for new versions
forge_version=26.1-62.0.9
forge_version_range=[62,)

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.0.19-beta

# Mod Properties
mod_id=examplemod
mod_group=com.example.examplemod
mod_version=1.0.0+26.1
mod_name=ExampleMod
mod_description=The description of your mod. \nAccepts multilines.
mod_author=ExampleAuthor
mod_credits=
mod_license=MIT
mod_icon=assets/examplemod/icon.png
mod_homepage=https://example.com/
mod_github=https://github.com/moritz-htk/MultiLoader-Template