pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'RelativityMC'
            url = 'https://repo.codemc.io/repository/relativitymc/'
        }
    }
}

rootProject.name = 'MultiLoader-Template'

include('common')
include('fabric')
include('neoforge')