plugins {
    id 'multiloader-loader'
}

loom {
    // Automatically convert AccessWideners to AccessTransformers if the file exists
    def awFile = project(':common').file("src/main/resources/${project.mod_id}.classtweaker")
    if (awFile.exists()) {
        convertAw2At(tasks.named('jar', Jar), ["${project.mod_id}.classtweaker"])
    }
}

repositories {
    maven {
        name = 'Forge'
        url = 'https://maven.minecraftforge.net/'
    }
}

dependencies {
    forgeUserdev "net.minecraftforge:forge:${project.forge_version}:userdev"
}